create schema train;
use train;

insert into products(name,info,price,quantity,type,brewery,abv,img) values("Sunny","It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",3.0,5,"Lager","LosBrewhos","6%","/photos/b1.jpg");
insert into products(name,info,price,quantity,type,brewery,abv,img) values("Igor","Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. ",1.0,5,"Bock","DarkCastle","8%","/photos/b6.jpg");
insert into products(name,info,price,quantity,type,brewery,abv,img) values("BlackNight","All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",5.0,5,"Stout","Elembivos","10%","/photos/b8.jpg");
insert into products(name,info,price,quantity,type,brewery,abv,img) values("CaltBier","The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",4.0,8,"Lager","GermViess","5%","/photos/b5.jpg");
insert into products(name,info,price,quantity,type,brewery,abv,img) values("Caliente","The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.",5.0,5,"Lager","LosBrewhos","5%","/photos/b3.jpg");
insert into products(name,info,price,quantity,type,brewery,abv,img) values("Flegermaus","The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, from 1914.",6.5,5,"Stout","Elembivos","9%","/photos/b7.jpg");
insert into products(name,info,price,quantity,type,brewery,abv,img) values("ViessDream","The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",5.0,8,"Viess","GermViess","6%","/photos/b4.jpg");
insert into products(name,info,price,quantity,type,brewery,abv,img) values("WierCult","It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.",5.0,8,"Viess","GermViess","8%","/photos/b2.jpg");
